version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_swift
    restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: swift_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
